// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.24.0

package database

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Follow struct {
	ID             uuid.UUID `json:"id"`
	UserID         uuid.UUID `json:"user_id"`
	FollowedUserID uuid.UUID `json:"followed_user_id"`
	CreatedAt      time.Time `json:"created_at"`
}

type Message struct {
	ID         uuid.UUID `json:"id"`
	Content    string    `json:"content"`
	FromUserID uuid.UUID `json:"from_user_id"`
	ToUserID   uuid.UUID `json:"to_user_id"`
}

type Post struct {
	ID          uuid.UUID `json:"id"`
	TextContent string    `json:"text_content"`
	UserID      uuid.UUID `json:"user_id"`
}

type PostImage struct {
	ID     uuid.UUID `json:"id"`
	Image  string    `json:"image"`
	PostID uuid.UUID `json:"post_id"`
}

type User struct {
	ID           uuid.UUID      `json:"id"`
	Username     string         `json:"username"`
	PasswordHash string         `json:"password_hash"`
	ProfileImage sql.NullString `json:"profile_image"`
}
